version: '2'

volumes:
  postgres_database:
    driver: local

services:

  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/b2share
      POSTGRES_DB: ${B2SHARE_POSTGRESQL_DBNAME}
      POSTGRES_USER: ${B2SHARE_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${B2SHARE_POSTGRESQL_PASSWORD}
    restart: always
    volumes:
    - postgres_database:/var/lib/postgresql/data/b2share
    ports: 
      - 5432:5432

  elasticsearch:
    #image: elasticsearch:6.8.11
    image: elasticsearch:7.8.1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mq:
    image: rabbitmq:latest
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: ${B2SHARE_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${B2SHARE_RABBITMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672